import React, { useState, useEffect } from 'react';
import { Lightbulb, AlertTriangle, CheckCircle, RefreshCw } from 'lucide-react';
import { get } from '../utils/api';

const priorityConfig = {
  High: { color: '#ef4444', bg: '#fee2e2', icon: <AlertTriangle size={18} /> },
  Medium: { color: '#f59e0b', bg: '#fef3c7', icon: <AlertTriangle size={18} /> },
  Low: { color: '#10b981', bg: '#d1fae5', icon: <CheckCircle size={18} /> },
};

export default function Recommendations() {
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('All');

  useEffect(() => {
    get('/recommendation/recommendations')
      .then(r => r.ok && r.json())
      .then(d => setRecs(d || []))
      .catch(() => setRecs([]))
      .finally(() => setLoading(false));
  }, []);

  const filtered = filter === 'All' ? recs : recs.filter(r => r.priority === filter);
  const counts = { High: recs.filter(r => r.priority === 'High').length, Medium: recs.filter(r => r.priority === 'Medium').length, Low: recs.filter(r => r.priority === 'Low').length };

  return (
    <div className="page-wrapper">
      <div className="page-header-row">
        <div>
          <h1>AI Recommendations</h1>
          <p>Actionable insights generated by the AI Prediction Service.</p>
        </div>
        <button className="btn btn-outline-blue" onClick={() => { setLoading(true); }} id="refresh-recs-btn">
          <RefreshCw size={16} /> Refresh
        </button>
      </div>

      {/* Summary */}
      <div className="finance-summary">
        <div className="finance-summary-item">
          <span>Total Alerts</span>
          <strong>{recs.length}</strong>
        </div>
        <div className="finance-summary-item">
          <span>High Priority</span>
          <strong style={{ color: '#ef4444' }}>{counts.High}</strong>
        </div>
        <div className="finance-summary-item">
          <span>Medium Priority</span>
          <strong style={{ color: '#f59e0b' }}>{counts.Medium}</strong>
        </div>
        <div className="finance-summary-item">
          <span>Low Priority</span>
          <strong style={{ color: '#10b981' }}>{counts.Low}</strong>
        </div>
      </div>

      {/* Filter pills */}
      <div className="filter-pills">
        {['All', 'High', 'Medium', 'Low'].map(f => (
          <button
            key={f}
            className={`filter-pill ${filter === f ? 'active' : ''}`}
            onClick={() => setFilter(f)}
            id={`filter-${f.toLowerCase()}`}
          >
            {f}
            {f !== 'All' && <span className="filter-count">{counts[f]}</span>}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="loading-state">Fetching recommendations...</div>
      ) : filtered.length === 0 ? (
        <div className="empty-state">
          <Lightbulb size={40} color="var(--text-muted)" />
          <p>No {filter !== 'All' ? filter.toLowerCase() + ' priority ' : ''}recommendations at this time.</p>
        </div>
      ) : (
        <div className="recs-list">
          {filtered.map(rec => {
            const cfg = priorityConfig[rec.priority] || priorityConfig.Low;
            return (
              <div key={rec.id} className="rec-card" style={{ borderLeft: `4px solid ${cfg.color}` }}>
                <div className="rec-card-icon" style={{ background: cfg.bg, color: cfg.color }}>
                  {cfg.icon}
                </div>
                <div className="rec-card-body">
                  <div className="rec-card-meta">
                    <span className="badge" style={{ background: cfg.bg, color: cfg.color }}>
                      {rec.priority} Priority
                    </span>
                    {rec.category && (
                      <span className="badge badge-primary">{rec.category}</span>
                    )}
                  </div>
                  <p className="rec-card-message">{rec.message}</p>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
